## Tratamento dos dados

Nesse notebook os dados são tratados de forma a tornar possível a análise

In [1]:
import pandas as pd
from utils.load_csv import load_csv
from utils.load_shp import load_shp

In [2]:
df_tse_2026 = load_csv('resultados_2026.csv')

df_observasampa = load_csv('observasampa.csv')

gdf_distritos = load_shp('distritos.shp')

In [3]:
df_tse_2026

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,...,NR_SECAO,CD_CARGO,DS_CARGO,NR_VOTAVEL,NM_VOTAVEL,QT_VOTOS,NR_LOCAL_VOTACAO,SQ_CANDIDATO,NM_LOCAL_VOTACAO,DS_LOCAL_VOTACAO_ENDERECO
0,06/10/2026,14:03:43,2026,2,Eleição Ordinária,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,E,...,100,6,Deputado Federal,5533,PAULO ALEXANDRE PEREIRA BARBOSA,1,1040,250002541120,EMEF. PROFA. JULIETA SYDOW MONTEIRO,"RUA BENJAMIM CONSTANT, S/N"
1,06/10/2026,14:03:43,2026,2,Eleição Ordinária,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,E,...,106,7,Deputado Estadual,22422,PAULO JORGE MANSUR NETO,1,1082,250002536393,EE. MOACIR THOMAZ DA SILVA,"RUA JOSÉ PEDRO LEITE, 200"
2,06/10/2026,14:03:43,2026,2,Eleição Ordinária,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,E,...,9,6,Deputado Federal,1345,ANIBAL ANTONIO MUNHOZ,1,1015,250002536718,EMEF. FRANCISCO RIBEIRO SOARES JÚNIOR,"RUA RIO DE JANEIRO, 517"
3,06/10/2026,14:03:43,2026,2,Eleição Ordinária,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,E,...,201,6,Deputado Federal,2211,LUCAS PAVANATO DE OLIVEIRA,46,1163,250002535995,EE PROF JOAQUIM FERREIRA PEDRO,"AV ANTONIO HADDAD, 703"
4,06/10/2026,14:03:43,2026,2,Eleição Ordinária,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,E,...,1,7,Deputado Estadual,22223,OSEIAS SANTOS DA SILVA,1,1015,250002536397,COLEGIO GAIA,"HANS STADEN, 718"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17043629,06/10/2026,14:03:43,2026,2,Eleição Ordinária,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,E,...,88,7,Deputado Estadual,55357,MARDQUEU SILVIO FRANCA FILHO,1,1015,250002540898,EMEF. DR. SANDOVAL JOSÉ DE ALMEIDA,"RUA BENJAMIN CONSTANT, 113"
17043630,06/10/2026,14:03:43,2026,2,Eleição Ordinária,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,E,...,41,6,Deputado Federal,7030,MANOEL JARDIM GOMES,1,1015,250002551049,EEPG PROF ANTONIO JOSINO DE ANDRADE,"R. JOVINA TRAJANO BORGES, 520-ITUVERAVA"
17043631,06/10/2026,14:03:43,2026,2,Eleição Ordinária,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,E,...,336,6,Deputado Federal,1290,TAMIR FELIPE BARCELAR E SANTOS,1,1244,250002548507,CEMPRE PROF. JOSE LIMONGI SOBRINHO,"RUA FELIPE SAWAYA, 595"
17043632,06/10/2026,14:03:43,2026,2,Eleição Ordinária,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,E,...,75,6,Deputado Federal,1003,OSVALDO DE QUADRO,1,1503,250002537956,EE. PROF. ELISEO MARSON,"RUA OSWALD ANDRADE, 255"
17043633,06/10/2026,14:03:43,2026,2,Eleição Ordinária,1,6259,Eleições Gerais Estaduais 2026,04/10/2026,E,...,506,7,Deputado Estadual,95,VOTO BRANCO,34,1171,-1,CEMEB PROFª. MARIA STELA SALES IZZO,"RUA PEDRO FERREIRA DOS SANTOS, 291"

In [4]:
df_observasampa

,Nome,Região,Período,Resultado
0,01.01.01 Quantidade de famílias em situação de...,Água Rasa (Distrito),2025,1560
1,01.01.01 Quantidade de famílias em situação de...,Água Rasa (Distrito),2022,2513
2,01.01.01 Quantidade de famílias em situação de...,Água Rasa (Distrito),2016,763
3,01.01.01 Quantidade de famílias em situação de...,Água Rasa (Distrito),2020,1386
4,01.01.01 Quantidade de famílias em situação de...,Água Rasa (Distrito),2021,1613
...,...,...,...,...
206193,Vítimas de acidentes de trânsito (por 100 mil ...,VILA PRUDENTE (Subprefeitura),2013,"978,0881"
206194,Vítimas de acidentes de trânsito (por 100 mil ...,VILA PRUDENTE (Subprefeitura),2021,"226,5429"
206195,Vítimas de acidentes de trânsito (por 100 mil ...,VILA PRUDENTE (Subprefeitura),2018,"160,0819"
206196,Vítimas de acidentes de trânsito (por 100 mil ...,VILA PRUDENTE (Subprefeitura),2015,"208,6941"
206197,Vítimas de acidentes de trânsito (por 100 mil ...,VILA PRUDENTE (Subprefeitura),2023,"226,2758"

In [5]:
gdf_distritos

,CD_REGIAO,NM_REGIAO,CD_UF,NM_UF,CD_MUN,NM_MUN,CD_DIST,NM_DIST,CD_RGINT,NM_RGINT,CD_RGI,NM_RGI,CD_CONCURB,NM_CONCURB,geometry
0,3,Sudeste,35,São Paulo,3500105,Adamantina,350010505,Adamantina,3505,Presidente Prudente,350019,Adamantina - Lucélia,NaN,NaN,"POLYGON ((-51.05218 -21.7097, -51.05232 -21.70..."
1,3,Sudeste,35,São Paulo,3500204,Adolfo,350020405,Adolfo,3507,São José do Rio Preto,350025,São José do Rio Preto,NaN,NaN,"POLYGON ((-49.61249 -21.2611, -49.61249 -21.26..."
2,3,Sudeste,35,São Paulo,3500303,Aguaí,350030305,Aguaí,3510,Campinas,350044,São João da Boa Vista,NaN,NaN,"POLYGON ((-47.01254 -22.00527, -47.01219 -22.0..."
3,3,Sudeste,35,São Paulo,3500402,Águas da Prata,350040205,Águas da Prata,3510,Campinas,350044,São João da Boa Vista,NaN,NaN,"POLYGON ((-46.71875 -21.95837, -46.71878 -21.9..."
4,3,Sudeste,35,São Paulo,3500402,Águas da Prata,350040210,São Roque da Fartura,3510,Campinas,350044,São João da Boa Vista,NaN,NaN,"POLYGON ((-46.73337 -21.87262, -46.73727 -21.8..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1037,3,Sudeste,35,São Paulo,3557105,Votuporanga,355710515,Simonsen,3507,São José do Rio Preto,350027,Votuporanga,NaN,NaN,"POLYGON ((-49.85227 -20.41665, -49.85289 -20.4..."
1038,3,Sudeste,35,São Paulo,3557154,Zacarias,355715405,Zacarias,3506,Araçatuba,350023,Birigui - Penápolis,NaN,NaN,"POLYGON ((-49.98507 -21.05306, -49.98518 -21.0..."
1039,3,Sudeste,35,São Paulo,3557204,Chavantes,355720405,Chavantes,3504,Marília,350015,Ourinhos,NaN,NaN,"POLYGON ((-49.73594 -23.03489, -49.74234 -23.0..."
1040,3,Sudeste,35,São Paulo,3557204,Chavantes,355720415,Irapé,3504,Marília,350015,Ourinhos,NaN,NaN,"POLYGON ((-49.72202 -23.0496, -49.72199 -23.04..."
1041,3,Sudeste,35,São Paulo,3557303,Estiva Gerbi,355730305,Estiva Gerbi,3510,Campinas,350043,Mogi Guaçu,3530706,Mogi Guaçu - Mogi Mirim/SP,"POLYGON ((-46.96444 -22.29548, -46.9661 -22.29..."